<!--
  %\VignetteEngine{knitr}
%\VignetteIndexEntry{d) US ZIP Choropleths}
-->

US ZIP Choropleths
===

You can create a choropleth of US ZIP codes with the function `zip_choropleth`. Note that what is rendered are actually US Zip Code Tabulated Areas (ZCTAs) from the US Census Bureau, not US Postal Service ZIP codes. [This page](https://www.census.gov/geo/reference/zctas.html) from the Census Bureau explains the differences. Also see `?zip.map` in the package `choroplethrZip` for more details.

Note that because of its size (~60MB) the `choroplethrZip` package is not hosted on CRAN. Rather, it is hosted on github [here](https://github.com/arilamstein/choroplethrZip/blob/master/README.md). You can install the package by typing:

```
library(choroplethr)

?install_choroplethrZip
install_choroplethrZip()
```

A side effect of the package being hosted on github is that vignettes hosted on CRAN cannot use the functions which depend on it. Therefore these examples do not generate images in this vignette, but will do so once you install `choroplethrZip` on your computer.

Here is a map of population estimates of all ZCTAs in New York state:

```
library(choroplethr)
library(choroplethrZip)

?df_pop_zip
data(df_pop_zip)

?zip_choropleth
zip_choropleth(df_pop_zip, state_zoom="new york")
```

# Data Requirements

The data.frame that you provide to `zip_choropleth` must have one column named "region" and one column named "value". Your entries for "region" must **exactly** match how regions are named in the map which choroplethr uses.  These names are defined in the object `zip.regions` along with some useful metadata:

```
library(choroplethrZip)

?zip.regions
data(zip.regions)
head(zip.regions)
```

In order to use choroplethr, you must use the naming convention in the "region" column of 
zip.regions. That is, you must use the string version of the ZIP code - i.e. you must include any leading zeroes. 

`zip_choropleth` does not render nationwide maps. You must specify a region to zoom in on with the parameters `state_zoom`, `county_zoom`, `msa_zoom` or `zip_zoom`.


# Exploring Data

Like all choroplethr functions, `zip_choropleth` allows you to specify the scale with the `num_colors` parameter. What makes `zip_choropleth` unique is the number of zoom options. You can view all ZIPs in a State, County, Metropolitan Statistical Area (MSA) as well as manually specify a number of ZIPs. We previously saw the population of New York State by ZIP. Here is an example of using the `county_zoom` parameter to zoom in on the five Counties of New York City:

```
# New York City is comprised of 5 counties: Bronx, Kings (Brooklyn), New York (Manhattan), 
# Queens, Richmond (Staten Island). Their numeric FIPS codes are:
nyc_fips = c(36005, 36047, 36061, 36081, 36085)
zip_choropleth(df_pop_zip,
               county_zoom=nyc_fips,
               title="2012 New York City ZCTA Population Estimates",
               legend="Population")
```

Here is an example of using the `zip_zoom` parameter to zoom in on two neighborhoods in Manhattan:
```
manhattan_les = c("10002", "10003", "10009")
manhattan_ues = c("10021", "10028", "10044", "10128")
zip_choropleth(df_pop_zip,
               zip_zoom=c(manhattan_les, manhattan_ues),
               title="2012 Lower and Upper East Side ZCTA Population Estimates",
               legend="Population")
```

Here is an example of using the `msa_zoom` parameter to zoom in on the entire New York Metropolitan Statistical Area (MSA):

```
zip_choropleth(df_pop_zip,
               msa_zoom="New York-Newark-Jersey City, NY-NJ-PA",
               title="2012 NY-Newark-Jersey City MSA\nZCTA Population Estimates",
               legend="Population")
```

# Advanced Options

Any customization outside the optional parameters presented above will require you to create a `ZipChoropleth` object.  choroplethr uses [R6](https://github.com/wch/R6) to take advantage of object-oriented programming.  Here is an example of using the `ggplot2_scale` on the base Choropleth object to customize the palette used.

```
library(ggplot2)

choro = ZipChoropleth$new(df_pop_zip)
choro$title = "2012 ZCTA Population Estimates"
choro$ggplot_scale = scale_fill_brewer(name="Population", palette=2, drop=FALSE)
choro$set_zoom_zip(state_zoom="new york", county_zoom=NULL, msa_zoom=NULL, zip_zoom=NULL)
choro$render()
```